name: Roda Testes unitários

on: [pull_request]

jobs:
  run-unit-tests:
    name: Roda Testes unitários
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run test:unit